FROM eclipse-temurin:21-jdk-jammy AS build

WORKDIR /backend

COPY tickets/.mvn .mvn
COPY tickets/mvnw ./
COPY tickets/pom.xml ./

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

COPY tickets/src src
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=build /backend/target/*.jar app.jar

ENV PORT=80
ENV JAVA_TOOL_OPTIONS="-XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:MaxRAMPercentage=70"

CMD ["/opt/java/openjdk/bin/java", "-jar", "/app/app.jar"]
