server:
  port: ${PORT:${SERVER_PORT:8082}}

app:
  frontend-url: ${FRONTEND_URL:http://localhost:5174}

spring:
  application:
    name: tickets

  main:
    lazy-initialization: true

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy
  

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tickets}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:changemeinprod!}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 5000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9090/realms/event-ticket-platform}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:9090/realms/event-ticket-platform/protocol/openid-connect/certs}

